"""empty message

Revision ID: a8b26cd587a7
Revises: bbec4775ae92
Create Date: 2024-02-01 10:33:38.783241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b26cd587a7'
down_revision = 'bbec4775ae92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coverImageUrl', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('numBooksInStore', sa.Integer(), nullable=True))
        batch_op.drop_column('cover_image_url')
        batch_op.drop_column('num_books_in_store')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_books_in_store', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cover_image_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('numBooksInStore')
        batch_op.drop_column('coverImageUrl')

    # ### end Alembic commands ###
