"""empty message

Revision ID: bbec4775ae92
Revises: 073edf38a724
Create Date: 2024-02-01 10:06:21.866456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbec4775ae92'
down_revision = '073edf38a724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('num_books_in_store', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('num_books_in_store')
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###
